name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/kanban-app:latest
            ${{ secrets.DOCKER_USERNAME }}/kanban-app:${{ github.sha }}

      - name: Test Secret Visibility
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "Secret is EMPTY"
          else
            echo "Secret is FOUND"
          fi